# Generated by Django 5.2.5 on 2025-08-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentbookfrontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=12345, max_length=50, unique=True, verbose_name='phone number'),
            preserve_default=False,
        ),
    ]
