# Generated by Django 5.2.5 on 2025-08-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentbookfrontend', '0003_subscriptionorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
