# Generated by Django 5.2.5 on 2025-08-21 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentbookfrontend', '0004_alter_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='subject_icons/')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='studentbookfrontend.class')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('chapter_icon', models.ImageField(blank=True, null=True, upload_to='chapter_icons/')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='studentbookfrontend.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='studentbookfrontend.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='studentbookfrontend.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='studentbookfrontend.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('chapter_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='studentbookfrontend.chapter')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='studentbookfrontend.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='studentbookfrontend.subject')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='studentbookfrontend.unit')),
            ],
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopic_name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('chapter_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='studentbookfrontend.chapter')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='studentbookfrontend.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='studentbookfrontend.subject')),
                ('topic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='studentbookfrontend.topic')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='studentbookfrontend.unit')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='studentbookfrontend.unit'),
        ),
    ]
