# Generated by Django 5.2.5 on 2025-08-21 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentbookfrontend', '0005_subject_chapter_unit_topic_subtopic_chapter_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='school_class',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='school_class',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='subtopic',
            old_name='school_class',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='school_class',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='school_class',
            new_name='course',
        ),
    ]
