# Generated by Django 5.2.5 on 2025-08-22 06:52

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentbookfrontend', '0006_rename_school_class_chapter_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='subject',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='course', chained_model_field='course', on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='studentbookfrontend.subject'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='unit',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='subject', chained_model_field='subject', on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='studentbookfrontend.unit'),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='chapter_name',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='unit', chained_model_field='unit', on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='studentbookfrontend.chapter'),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='subject',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='course', chained_model_field='course', on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='studentbookfrontend.subject'),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='topic_name',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='chapter_name', on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='studentbookfrontend.topic'),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='unit',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='subject', chained_model_field='subject', on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='studentbookfrontend.unit'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='chapter_name',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='unit', chained_model_field='unit', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='studentbookfrontend.chapter'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='course', chained_model_field='course', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='studentbookfrontend.subject'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='unit',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='subject', chained_model_field='subject', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='studentbookfrontend.unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='subject',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='course', chained_model_field='course', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='studentbookfrontend.subject'),
        ),
    ]
